### ISSUE TITLE
bug: `ingress.bluemix.net/rewrite-path` not working

### ISSUE THREAD

**Issue by wxharry** [IBM-Cloud/iks-ingress-controller#3]
Hi, I am currently building a ray cluster in k8s provided by IBM cloud. I want to expose the ray dashboard to the public network using ingress to path `/dashboard` but got `404`. I have tested the service and port is working properly. And I tried [rewrite example](https://kubernetes.github.io/ingress-nginx/examples/rewrite/) provided by k8s but nothing changed.

So I found this repo and tried to use the `ingress.bluemix.net/rewrite-path` mentioned [here](https://github.com/IBM-Cloud/iks-ingress-controller/blob/master/docs/annotations.md#rewrite-paths-rewrite-path) but still no luck.

I am wondering if I missed anything here? I have attached my yaml file for ingress. Thank you for the help
``` yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ray-ingress
  labels:
    app: ray-ingress
  annotations:
    kubernetes.io/ingress.class: public-iks-k8s-nginx
    ingress.bluemix.net/rewrite-path: "serviceName=raycluster-kuberay-head-svc rewrite=/;"
spec:
  tls:
  - hosts:
    - mycluster-us-south-<id>-0000.us-south.containers.appdomain.cloud
    secretName: mycluster-us-south-<id>-0000
  rules:
  - host: mycluster-us-south-<id>-0000.us-south.containers.appdomain.cloud
    http:
      paths:
      - path: /kuberay
        pathType: Prefix
        backend:
          service:
            name: raycluster-kuberay-head-svc
            port:
              number: 8265
```

Also, I found that the examples are not up-to-date according to the [k8s official usage](https://kubernetes.github.io/ingress-nginx/user-guide/basic-usage/), which might be the reason causing this failure.
